version: '3.8'
services:
  web:
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
    build: .
    ports:
      - "8000:8000"
  db:
    image: "postgres:15.4-bullseye"
    environment:
      POSTGRES_DB: "yourdb"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
  nginx:
    image: nginx:1.25.2-alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./ui/build:/ui/build # this line ensures that Nginx can access your React files
      - ./ui/build:/usr/share/nginx/html # this line ensures that Nginx can access your React files
    depends_on:
      - web
