version: '3.8'
services:
  web:
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/lotr-home
    build: .
    ports:
      - "8000:8000"
  db:
    image: "postgres:15.4-bullseye"
    environment:
      POSTGRES_DB: "lotr-home"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
  nginx:
    image: nginx:1.25.2-alpine-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./ui/build:/ui/build # this line ensures that Nginx can access your React files
      - ./ui/build:/usr/share/nginx/html # this line ensures that Nginx can access your React files
    depends_on:
      - web
